site_name: INDUS Starter Site
age_verification:
    - title: Age Verification
    - text: To visit this site you must confirm that you are 21+ years old.
    - button: Confirm
groups:
    - group: 
        title: Indica
    - group: 
        title: Sativa
    - group: 
        title: Hybrid
products:
    - product:
        title: Sour Diesel OG
        image: /assets/images/SourOGGroup.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Indica
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Pink Cookies
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Sativa
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Sour Diesel OG
        image: /assets/images/SourOGGroup.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Indica
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Pink Cookies
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Sativa
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Lorem Ipsum
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Hybrid
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'   
    - product:
        title: Lorem Ipsum
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Hybrid
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'                      
    - product:
        title: Sour Diesel OG
        image: /assets/images/SourOGGroup.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Indica
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'            
    - product:
        title: Pink Cookies
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Sativa
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Sour Diesel OG
        image: /assets/images/SourOGGroup.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Indica
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Pink Cookies
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Sativa
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Sour Diesel OG
        image: /assets/images/SourOGGroup.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Indica
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Pink Cookies
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Sativa
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Sour Diesel OG
        image: /assets/images/SourOGGroup.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Indica
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Pink Cookies
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Sativa
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Pink Cookies
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Sativa
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
    - product:
        title: Pink Cookies
        image: /assets/images/PinkCookies.png
        description: This potent crowd favorite packs in the flavor and an incredible body high. Cultivated in accordance with legacy strains, we have engineered this flower to contain higher levels of terpenes resulting in epic flavor.
        strain-type: 
            - Sativa
        additional-info: This potent crowd favorite packs in the flavor and an incredible body high and more.
        stat-thc: '23g'
        stat-cbd: '0.6g'
                  